config/routes.rb
Raisy::Application.routes.draw do
  
  mount WeixinRailsMiddleware::Engine, at: "/"
    # root 'pages#index'
    root 'fancy#index'
    
    devise_for :users,:controllers => {:registrations => "registrations"}
    
    devise_scope :user do 
      get 'signup_social_user', to: 'registrations#signup_social_user'
    end
    
    get "/auth/failure", to: "users#omniauth_failure"
    get "/auth/twitter/callback", to: "users#omniauth_callback"
    get "/auth/facebook/callback", to: "users#omniauth_callback"
    
    match "/user/verify" => "users#verify_user", via: [:get, :post]
    match "/user/lookup" => "users#lookup_user", via: [:get, :post]

    namespace :admin do
        root 'dashboard#index'
        
        resources :collections do
            resources :categories
        end

        resources :product_categories do
          match 'product_categories/new', to: 'product_categories#subclassnew',via:[:get], as: :new_product_category_subclass
          post 'product_categories', to: 'product_categories#subclasscreate', as: :create_product_category_subclass
          get 'product_categories', to: 'product_categories#subclassindex', as: :index_product_category_subclass
          delete 'product_categories/:id', to: 'product_categories#subclassdestroy', as: :delete_product_category_subclass
          get  'product_categories/:id/edit', to: 'product_categories#subclassedit', as: :edit_product_category_subclass
          get  'product_categories/:id', to: 'product_categories#subclassshow', as: :show_product_category_subclass
          match  'product_categories/:id', to: 'product_categories#subclassupdate',via: [:patch,:put], as: :update_product_category_subclass

          get  'product_categories/ajax/select', to: 'product_categories#sublass_ajax_select', as: :show_product_category_subclass_ajax_select
          resources :product_categories
        end

        get 'products/ajax',to: 'products#show_pager_data', as: :load_products_show_pager_data
        post 'products/ajax',to: 'products#show_pager_data', as: :products_show_pager_data
        resources :products do
          get '/option_group/edit', to: 'products#edit_option_group', as: :edit_option_group
          match '/option_group/save' => 'products#save_option_group', via: [:post, :patch], as: :save_option_group
          delete '/option_group/delete', to: 'products#delete_option_group', as: :delete_option_group
          post '/option_group_property/:id/save', to: 'products#save_option_group_property', as: :save_option_group_property
          delete '/option_group_property/:id/delete', to: 'products#delete_option_group_property', as: :delete_option_group_property
        end
        
        resources :invites
        resources :organizations
        post 'organizations/ajax',to: 'organizations#ajax_pager_data', as: :organizations_page_ajax
        resources :users
        
        resources :campaigns do
            resources :orders
        end
        post 'campaigns/ajax',to: 'campaigns#ajax_pager_data', as: :campaigns_page_ajax
        
        resources :settings
        resources :vendors

        resources :tags
        post 'tags/ajax',to: 'tags#ajax_pager_data', as: :tags_page_ajax
        post  'tags/search_ajax',to:"tags#search_ajax", as: :tags_search_ajax
        post  'tags/ajax_delete',to: 'tags#ajax_delete', as: :tags_ajax_delete
        
        get 'campaign_stories', to: 'campaigns#stories'
        get 'campaign_story/:id', to: 'campaigns#story'
        post 'campaign_save_story', to: 'campaigns#save_story'
        
        get 'campaign_images', to: 'campaigns#images'
        get 'campaign_image', to: 'campaigns#image'
        get 'campaign_delete_image', to: 'campaigns#delete_image'
        post 'campaign_save_image', to: 'campaigns#save_image'
        
        get 'default_email_message', to: 'settings#default_email_message'
        post 'save_default_email_message', to: 'settings#save_default_email_message'
        get 'default_chairperson_email_message', to: 'settings#default_chairperson_email_message'
        post 'save_default_chairperson_email_message', to: 'settings#save_default_chairperson_email_message'
        
        get 'campaign_bulkshippinginfo/:id', to: 'campaigns#bulkshippinginfo', as: :campaign_bulkshippinginfo
        post 'campaign_bulkshippinginfo/:id/create', to: 'campaigns#create_bulkshippinginfo', as: :campaign_bulkshippinginfos
        patch 'campaign_bulkshippinginfo/:id', to: 'campaigns#update_bulkshippinginfo'
        
        get 'product_collections/:id', to: 'products#prod_collections', as: :product_collections
        
        namespace :reports do
          root 'reportsboard#index'
          get 'campvisit_log/report',to: 'campaign_visit_log#reportindex', as: :campvisit_log_report
          post 'campvisit_log/report',to: 'campaign_visit_log#reportsearch', as: :campvisit_log_report_search
          get 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation', as: :campvisit_log_report_visit_share_donation
          post 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation_ajax', as: :ajax_campvisit_log_report_visit_share_donation
          get 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log', as: :campvisit_log_report_visit_log
          post 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log_ajax', as: :ajax_campvisit_log_report_visit_log
        end
        
        resources :questionnaires
      
        get 'mall_settings', to: 'mall#settings', as: :mall_settings
        post 'save_mall_settings', to: 'mall#save_settings', as: :save_mall_settings

        resources :express_upload
        get 'express/load_excle',to: 'express_upload#load_excle',as: :express_load_excle_ajax
        get 'express/validate',to: 'express_upload#validate_check',as: :express_validate_ajax
        get 'express/update',to: 'express_upload#update_data',as: :express_update_ajax
        get 'express/donload',to: 'express_upload#donload',as: :express_donload
        
        get 'weishop_settings', to: 'weishop#settings', as: :weishop_settings
        post 'save_weishop_settings', to: 'weishop#save_settings', as: :save_weishop_settings
        
    end

  #Express
  get 'order_express/:item_id/:courier_number', to: 'express#order_express', as: :order_express
  get 'order_express_ajax/:item_id/:courier_number', to: 'express#order_express_ajax', as: :order_express_ajax
  get 'order_express_ajax', to: 'express#order_express_ajax', as: :order_express_ajax_get


    # Mall
    scope 'mall' do
      root 'mall#home', as: :mall_home
      match 'search' => 'mall#search', via: [:get, :post], as: :mall_search
      match 'search_page' => 'mall#search_page', via: [:get, :post], as: :mall_search_page
      get 'orders', to: 'mall#orders', as: :mall_orders
      get 'orders_page', to: 'mall#orders_page', as: :mall_orders_page
      get 'order_detail/:id', to: 'mall#order_detail', as: :mall_order_detail
    end

    resources :collections
    resources :organizations


  get 'shopmall/product/:product_id', to: 'shop_mall#product', as: :shop_mall_product
  get 'shopmall/pay', to: 'shop_mall#pay', as: :shop_mall_product_pay
  # get 'shopmall/product_id', to: 'shop_mall#product', as: :shop_mall_product_view
    #personal_story
  get 'checkout/lzds', to: 'campaign_ngo#lzds', as: :campagin_ngo_lzds
  get 'campaginngo/lzds_supporters', to: 'campaign_ngo#lzds_supporters', as: :campagin_ngo_lzds_supporters

  get 'checkout/lovehb', to: 'campaign_ngo#lovehb', as: :campagin_ngo_lovehb
  get 'campaginngo/lovehb_supporters', to: 'campaign_ngo#lovehb_supporters', as: :campagin_ngo_lovehb_supporters

  get 'checkout/xgst', to: 'campaign_ngo#xgst', as: :campagin_ngo_xgst
  get 'campaginngo/xgst_supporters', to: 'campaign_ngo#xgst_supporters', as: :campagin_ngo_xgst_supporters

  get 'checkout/:id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview_checkout
  get ':id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview
  get 'campaginngo/campaignview_supporters', to: 'campaign_ngo#campaignview_supporters', as: :campagin_ngo_campaignview_supporters
  get "checkout/:ids", to:"product#index",constraints: { ids: /hotsale_\S+/ },as: :hotsale_index
  get 'checkout/:procamp', to: 'shop#product_weixin',constraints: { procamp: /procamp_\S+_[0-9]+/ }, as: :shop_product_weixin_pay
  get "checkout/:partyid", to:"shop_mall#party_index",constraints: { partyid: /party_\S+/ },as: :party_index_weixin
  get 'checkout/shgs', to: 'campaign_ngo#shgs', as: :campagin_ngo_shgs
  get 'campaginngo/shgs_supporters', to: 'campaign_ngo#shgs_supporters', as: :campagin_ngo_shgs_supporters

  get 'checkout/xyetjk', to: 'campaign_ngo#xyetjk', as: :campagin_ngo_xyetjk
  get 'campaginngo/xyetjk_supporters', to: 'campaign_ngo#xyetjk_supporters', as: :campagin_ngo_xyetjk_supporters

  get 'checkout/lbxgy', to: 'campaign_ngo#lbxgy', as: :campagin_ngo_lbxgy
  get 'campaginngo/lbxgy_supporters', to: 'campaign_ngo#lbxgy_supporters', as: :campagin_ngo_lbxgy_supporters

  get 'checkout/lbflower', to: 'campaign_ngo#lbflower', as: :campagin_ngo_lbflower
  get 'campaginngo/lbflower_supporters', to: 'campaign_ngo#lbflower_supporters', as: :campagin_ngo_lbflower_supporters

  get 'checkout/lbpulushi', to: 'campaign_ngo#lbpulushi', as: :campaign_ngo_lbpulushi
  get 'campaginngo/lbpulushi_supporters', to: 'campaign_ngo#lbpulushi_supporters', as: :campagin_ngo_lbpulushi_supporters
  
  post 'campaginngo/confirmation', to: 'campaign_ngo#confirmation', as: :campaign_ngo_checkout_confirmation
  post 'campaginngo/confirmation_weixin', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin
  post 'campaginngo/confirmation_weixin/:campaign_id', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin_bycampaign

app/models/collection.rb
class Collection < ActiveRecord::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged

    # Try building a slug based on the following fields in
    # increasing order of specificity.
    def slug_candidates
        [
            :name,
            [:name, "#{Collection.where(name: name).count + 1}"]
        ]
    end


    scope :active, -> { where(active: true).order(:sort_order) }
    scope :isnot_destroy,->{where(is_destroy:false)}

    has_many :categories, :dependent => :destroy
    has_and_belongs_to_many :products,->{where is_destroy: false}
    has_many :campaigns

    validates :name, presence: true

    def tile_size
        #if the number of products is greater than 4, return 4 (puts 3 tiles per row)
        #if the number of products is less than or equal to 4, return 6 (puts 2 tiles per row)
        self.products.count > 4 ? 4 : 6
    end

end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::ApplicationController

    def index
        @collections = Collection.isnot_destroy.order(:id)
    end

    def show
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
    end

    def new
        @collection = Collection.new
    end

    def create
        @collection = Collection.new(collection_params)

        # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
        if !@collection.valid?
            message = ''
            @collection.errors.each do |key, error|
                message = message + key.to_s.humanize + ' ' + error.to_s + ', '
            end
            flash.now[:danger] = message[0...-2]
            render action: "new" and return
        end

        @collection.save

        if params[:collection_image].present? && params[:remove_item_image]=="no"
            preloaded = Cloudinary::PreloadedFile.new(params[:collection_image])
            if preloaded.valid?
                @collection.update_attribute(:picture, preloaded.identifier)
            end
        end

        redirect_to admin_collections_url, flash: { success: "组合已创建" }

    end

    def edit
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
    end

    def update
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
        @collection.assign_attributes(collection_params)

        # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
        if !@collection.valid?
            message = ''
            @collection.errors.each do |key, error|
                message = message + key.to_s.humanize + ' ' + error.to_s + ', '
            end
            flash.now[:danger] = message[0...-2]
            render action: "new" and return
        end

        @collection.save
        
        if params[:remove_item_image]=="yes"
           @collection.update_attribute(:picture, "")
        else
          if params[:collection_image].present?
              preloaded = Cloudinary::PreloadedFile.new(params[:collection_image])
              if preloaded.valid?
                  @collection.update_attribute(:picture, preloaded.identifier)
              end
          end
        end

        redirect_to admin_collections_url, flash: { success: "组合已更新" }
    end

    def destroy
        @collection = Collection.friendly.find(params[:id])
        
        if !@collection
          redirect_to admin_collections_url, flash: { danger: "该组合未找到" } and return
        end
        
        if @collection.campaigns.count>0
          redirect_to admin_collections_url, flash: { 
            danger: "组合正在使用，无法删除" } and return
        end
        
        if @collection.products.count>0
          redirect_to admin_collections_url, flash: { 
            danger: "组合正在使用，无法删除" } and return
        end

        @collection.update(is_destroy:true)
        redirect_to admin_collections_url, flash: { success: "组合已删除" }
    end

    private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def collection_params
        params.require(:collection).permit :name, :description, :landing_page_html, :donation_percentage, :picture, :active, :sort_order
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

    def index
        @collections = Collection.isnot_destroy.active
    end

    def show
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
    end

end

app/helpers/admin/collections_helper.rb
module Admin::CollectionsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/index.html.erb
<div id="collections">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h3>Choose a program</h3>
                <p>Once you've decided what you would like your group to sell, we'll help you set up an online fundraising page in minutes!</p>
            </div>
        </div>

        <div class="row">
            <% @collections.each do |collection| %>
            <div class="col-md-4">
                <div class="well">
                    <a href="<%= collection_path(collection) %>">
                        <div class="collection-image-container">
                            <%= cl_image_tag collection.picture, width: 200, height: 200, crop: :limit, class: 'img-responsive' %>
                            <h4><%= collection.name %></h4>
                        </div>
                    </a>
                </div>
            </div>
            <% end %>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div style="text-align: center; padding: 40px">
                    <p>Don't see a program that's a good fit for your group?  Get in touch!  We work with lots of groups on custom campaigns.</p>
                    <%= link_to "Let's Talk", '#', class: 'btn btn-primary launch-invite-modal' %>
                </div>
            </div>
        </div>

    </div>
</div>

<div id="invite-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="invite-modal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header modal-header-purple">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Get in touch!</h4>
        </div> <!-- /.modal-header -->

        <form role="form" class="invite-form" data-type="modal-form">
        <div class="modal-body">
            <p style="margin-bottom: 20px;">Currently we're working closely with schools to help refine our programs and we'd love to help you!</p>
              <div class="form-group">
                <label for="nameInput" class="control-label">Name</label>
                <input type="name" class="form-control" id="nameInput" placeholder="Name" name="invite[name]">
              </div>
              <div class="form-group">
                <label for="emailInput" class="control-label">E-Mail</label>
                <input type="email" class="form-control" id="emailInput" placeholder="E-Mail" name="invite[email]">
              </div>
              <div class="form-group">
                <label for="orgInput" class="control-label">Organization</label>
                <input type="organization" class="form-control" id="orgInput" placeholder="School, Organization, Team" name="invite[organization]">
              </div>
                <input type="hidden" name="invite[source]" value="collection">
                <input type="hidden" id="invite_collection_id" name="invite[collection_id]" value="0"/>
            <p class="error-message" style="display: none">Hmm, there was a problem with your entries, please try again!</p>
        </div> <!-- end of modal body -->

        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">
                <span class="text">Submit</span> <span class="loader" style="display:none"></span>
            </button>
        </div> <!-- /.modal-footer -->
        </form>

        <div class="success-message" style="display: none">
            <div class="modal-body">
                Thanks, we'll get back to you within 1 day!
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><span>Close</span></button>
            </div>
        </div>

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

app/views/collections/show.html.erb
<div id="collections" style="background-image: linear-gradient(#681e57, #c9d5da);">

    <div class="collection-overview">
        <div class="container">
            <div class="well well-white hero-content">
                <div class="row">
                    <div class="col-md-7">
                        <%= cl_image_tag @collection.picture, class: 'img-responsive' %>
                    </div>
                    <div class="col-md-5">
                        <div class="headline">
                            <h2 style="margin-top:5px;"><%= @collection.name %></h2>
                            <%= raw(@collection.description) %>
                            <%= raw(@collection.landing_page_html) %>
                        </div>
                    </div>
                </div>
                <div class="row more-information">
                    <div class="col-md-7">
                        <!-- form role="form" class="invite-form">
                            <div>
                                <h4>Want more information?  No problem!</h4>
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control" id="emailInput" placeholder="Enter your email address ..." name="invite[email]">
                            </div>
                            <input type="hidden" name="invite[collection_id]" value="<%#= @collection.id %>">
                            <input type="hidden" name="invite[source]" value="<%#= @collection.name %> Landing Page Lead">
                            <button type="submit" class="btn btn-default">
                                <span class="text">Get Your Free Information Packet</span> <span class="loader loader-black" style="display:none"></span>
                            </button>
                        </form>
                        <h3 class="success-message" style="display: none">Thanks, we'll get back to you within 24 hours!</h3>
                        <h3 class="error-message" style="display: none">Hmm, there was a problem with your entries, please try again!</h3 -->
                        <div class="col-md-3">
                            <!--<%= image_tag "anne.jpg", class: 'img-responsive img-circle', style: 'height:100px' %>-->
                        </div>
                        <div class="col-md-9">
                             <!--<h4>"Raisy helped us to raise more money in less time without all of the usual hassles.  We can't wait to do another fundraiser with Raisy!"</h4>-->
                        </div>
                         <!--<div style="font-style:italic;color:gray;margin-left:50px;margin-top:120px;">Anne Dizon, Teacher at Saint Clement in Hayward, California</div>-->
                    </div>
                    <div class="col-md-5 landing-page-fundraiser-button" style="margin-top:20px;">
                        <div class="online-orders">
                            <p>
                                <%= link_to 'Start Your Fundraiser', new_campaign_path(collection: @collection.slug), class: 'btn btn-primary btn-block' %>
                            </p>
                            <%= image_tag "comp.png", class: 'pull-left' %>
                            <h2>Collect Orders Online!</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="collection-details">
        <div class="container">
            <div class="well well-white">

                <div class="row">
                    <div class="col-md-12">
                        <h2 style="margin-top:5px;margin-bottom:20px;">Products in the <%= @collection.name %> Collection</h2>
                    </div>
                </div>

                <div class="row">
                <% @collection.products.order(:id).each do |product| %>

                    <div class="col-md-4">
                        <a href="#" data-toggle="modal" data-target="<%= "#product-modal-#{product.id}" %>" class="product-tile">
                            <div class="well well-white" style="text-align: center">
                                <div class="image-container">
                                    <%= cl_image_tag product.picture, width: 232, height: 232, crop: :fill, class: 'img-responsive', style: 'margin:auto;' %>
                                </div>
                                <h4><%= truncate(product.name, length: 25) %><br/>$<%= short_price(product.total_price) %></h4>
                            </div>
                        </a>
                    </div>
                    <div id="<%= "product-modal-#{product.id}" %>" class="modal fade product-modal" tabindex="-1" role="dialog" aria-labelledby="<%= "product-modal-#{product.id}" %>" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header" style="border-bottom:none;">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                </div> <!-- /.modal-header -->

                                <div class="modal-body product-form">
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div class="image-container" style="width: 100%; padding: 20px; border: 1px solid gainsboro; border-radius: 3px">
                                                <%= cl_image_tag product.picture, class: 'img-responsive', style: "margin: auto; max-height: 250px;" %>
                                            </div>
                                        </div>
                                        <div class="col-md-5">
                                            <h4 class="visible-md visible-lg"><%= product.name %></h4>
                                            <p style="margin-bottom: 15px;"><%= product.description.html_safe %></p>
                                            <h2 style="margin: 15px 0px">$<%= short_price(product.total_price) %></h2>
                                        </div>
                                    </div>
                                </div> <!-- end of modal body -->
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!--/#modal -->

                <% end %> <!-- end collections iterator -->
                </div>

            </div>

            <div class="well well-white">

                <div class="row">
                    <div class="col-md-8">
                        <div class="start-today">
                            <h2>Start your online fundraiser today!</h2>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div style="text-align:center;">
                            <%= link_to 'Get Started Now!', new_campaign_path(collection: @collection.slug), class: 'btn btn-primary btn-small' %>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="contact-us" style="background:#681e57; padding:50px 0px; color:white;">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 style="margin-top:0px; color:white;">Want help getting started?</h2>
                    <p>Just get in touch and we'll get back with you in 24 hours!<br/></p>
                </div>
                <div class="col-md-6">
                    <form role="form" class="invite-form">
                      <div class="form-group">
                        <label for="nameInput" class="control-label">Name</label>
                        <input type="name" class="form-control" id="nameInput" placeholder="Name" name="invite[name]">
                      </div>
                      <div class="form-group">
                        <label for="emailInput" class="control-label">E-Mail</label>
                        <input type="email" class="form-control" id="emailInput" placeholder="E-Mail" name="invite[email]">
                      </div>
                      <div class="form-group">
                        <label for="orgInput" class="control-label">Organization</label>
                        <input type="organization" class="form-control" id="orgInput" placeholder="School, Organization, Team" name="invite[organization]">
                      </div>
                        <input type="hidden" name="invite[collection_id]" value="<%= @collection.id %>">
                        <input type="hidden" name="invite[source]" value="<%= @collection.name %> Landing Page Footer">
                        <button type="submit" class="btn btn-default">
                            <span class="text">Submit</span> <span class="loader loader-black" style="display:none"></span>
                        </button>
                    </form>
                    <p class="success-message" style="display: none">Thanks, we'll get back to you within 1 day!</p>
                    <p class="error-message" style="display: none">Hmm, there was a problem with your entries, please try again!</p>
                </div>
            </div>
        </div>
    </div>

</div>