config/routes.rb
Raisy::Application.routes.draw do
  
  mount WeixinRailsMiddleware::Engine, at: "/"
    # root 'pages#index'
    root 'fancy#index'
    
    devise_for :users,:controllers => {:registrations => "registrations"}
    
    devise_scope :user do 
      get 'signup_social_user', to: 'registrations#signup_social_user'
    end
    
    get "/auth/failure", to: "users#omniauth_failure"
    get "/auth/twitter/callback", to: "users#omniauth_callback"
    get "/auth/facebook/callback", to: "users#omniauth_callback"
    
    match "/user/verify" => "users#verify_user", via: [:get, :post]
    match "/user/lookup" => "users#lookup_user", via: [:get, :post]

    namespace :admin do
        root 'dashboard#index'
        
        resources :collections do
            resources :categories
        end

        resources :product_categories do
          match 'product_categories/new', to: 'product_categories#subclassnew',via:[:get], as: :new_product_category_subclass
          post 'product_categories', to: 'product_categories#subclasscreate', as: :create_product_category_subclass
          get 'product_categories', to: 'product_categories#subclassindex', as: :index_product_category_subclass
          delete 'product_categories/:id', to: 'product_categories#subclassdestroy', as: :delete_product_category_subclass
          get  'product_categories/:id/edit', to: 'product_categories#subclassedit', as: :edit_product_category_subclass
          get  'product_categories/:id', to: 'product_categories#subclassshow', as: :show_product_category_subclass
          match  'product_categories/:id', to: 'product_categories#subclassupdate',via: [:patch,:put], as: :update_product_category_subclass

          get  'product_categories/ajax/select', to: 'product_categories#sublass_ajax_select', as: :show_product_category_subclass_ajax_select
          resources :product_categories
        end

        get 'products/ajax',to: 'products#show_pager_data', as: :load_products_show_pager_data
        post 'products/ajax',to: 'products#show_pager_data', as: :products_show_pager_data
        resources :products do
          get '/option_group/edit', to: 'products#edit_option_group', as: :edit_option_group
          match '/option_group/save' => 'products#save_option_group', via: [:post, :patch], as: :save_option_group
          delete '/option_group/delete', to: 'products#delete_option_group', as: :delete_option_group
          post '/option_group_property/:id/save', to: 'products#save_option_group_property', as: :save_option_group_property
          delete '/option_group_property/:id/delete', to: 'products#delete_option_group_property', as: :delete_option_group_property
        end
        
        resources :invites
        resources :organizations
        post 'organizations/ajax',to: 'organizations#ajax_pager_data', as: :organizations_page_ajax
        resources :users
        
        resources :campaigns do
            resources :orders
        end
        post 'campaigns/ajax',to: 'campaigns#ajax_pager_data', as: :campaigns_page_ajax
        
        resources :settings
        resources :vendors

        resources :tags
        post 'tags/ajax',to: 'tags#ajax_pager_data', as: :tags_page_ajax
        post  'tags/search_ajax',to:"tags#search_ajax", as: :tags_search_ajax
        post  'tags/ajax_delete',to: 'tags#ajax_delete', as: :tags_ajax_delete
        
        get 'campaign_stories', to: 'campaigns#stories'
        get 'campaign_story/:id', to: 'campaigns#story'
        post 'campaign_save_story', to: 'campaigns#save_story'
        
        get 'campaign_images', to: 'campaigns#images'
        get 'campaign_image', to: 'campaigns#image'
        get 'campaign_delete_image', to: 'campaigns#delete_image'
        post 'campaign_save_image', to: 'campaigns#save_image'
        
        get 'default_email_message', to: 'settings#default_email_message'
        post 'save_default_email_message', to: 'settings#save_default_email_message'
        get 'default_chairperson_email_message', to: 'settings#default_chairperson_email_message'
        post 'save_default_chairperson_email_message', to: 'settings#save_default_chairperson_email_message'
        
        get 'campaign_bulkshippinginfo/:id', to: 'campaigns#bulkshippinginfo', as: :campaign_bulkshippinginfo
        post 'campaign_bulkshippinginfo/:id/create', to: 'campaigns#create_bulkshippinginfo', as: :campaign_bulkshippinginfos
        patch 'campaign_bulkshippinginfo/:id', to: 'campaigns#update_bulkshippinginfo'
        
        get 'product_collections/:id', to: 'products#prod_collections', as: :product_collections
        
        namespace :reports do
          root 'reportsboard#index'
          get 'campvisit_log/report',to: 'campaign_visit_log#reportindex', as: :campvisit_log_report
          post 'campvisit_log/report',to: 'campaign_visit_log#reportsearch', as: :campvisit_log_report_search
          get 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation', as: :campvisit_log_report_visit_share_donation
          post 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation_ajax', as: :ajax_campvisit_log_report_visit_share_donation
          get 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log', as: :campvisit_log_report_visit_log
          post 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log_ajax', as: :ajax_campvisit_log_report_visit_log
        end
        
        resources :questionnaires
      
        get 'mall_settings', to: 'mall#settings', as: :mall_settings
        post 'save_mall_settings', to: 'mall#save_settings', as: :save_mall_settings

        resources :express_upload
        get 'express/load_excle',to: 'express_upload#load_excle',as: :express_load_excle_ajax
        get 'express/validate',to: 'express_upload#validate_check',as: :express_validate_ajax
        get 'express/update',to: 'express_upload#update_data',as: :express_update_ajax
        get 'express/donload',to: 'express_upload#donload',as: :express_donload
        
        get 'weishop_settings', to: 'weishop#settings', as: :weishop_settings
        post 'save_weishop_settings', to: 'weishop#save_settings', as: :save_weishop_settings
        
    end

  #Express
  get 'order_express/:item_id/:courier_number', to: 'express#order_express', as: :order_express
  get 'order_express_ajax/:item_id/:courier_number', to: 'express#order_express_ajax', as: :order_express_ajax
  get 'order_express_ajax', to: 'express#order_express_ajax', as: :order_express_ajax_get


    # Mall
    scope 'mall' do
      root 'mall#home', as: :mall_home
      match 'search' => 'mall#search', via: [:get, :post], as: :mall_search
      match 'search_page' => 'mall#search_page', via: [:get, :post], as: :mall_search_page
      get 'orders', to: 'mall#orders', as: :mall_orders
      get 'orders_page', to: 'mall#orders_page', as: :mall_orders_page
      get 'order_detail/:id', to: 'mall#order_detail', as: :mall_order_detail
    end

    resources :collections
    resources :organizations


  get 'shopmall/product/:product_id', to: 'shop_mall#product', as: :shop_mall_product
  get 'shopmall/pay', to: 'shop_mall#pay', as: :shop_mall_product_pay
  # get 'shopmall/product_id', to: 'shop_mall#product', as: :shop_mall_product_view
    #personal_story
  get 'checkout/lzds', to: 'campaign_ngo#lzds', as: :campagin_ngo_lzds
  get 'campaginngo/lzds_supporters', to: 'campaign_ngo#lzds_supporters', as: :campagin_ngo_lzds_supporters

  get 'checkout/lovehb', to: 'campaign_ngo#lovehb', as: :campagin_ngo_lovehb
  get 'campaginngo/lovehb_supporters', to: 'campaign_ngo#lovehb_supporters', as: :campagin_ngo_lovehb_supporters

  get 'checkout/xgst', to: 'campaign_ngo#xgst', as: :campagin_ngo_xgst
  get 'campaginngo/xgst_supporters', to: 'campaign_ngo#xgst_supporters', as: :campagin_ngo_xgst_supporters

  get 'checkout/:id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview_checkout
  get ':id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview
  get 'campaginngo/campaignview_supporters', to: 'campaign_ngo#campaignview_supporters', as: :campagin_ngo_campaignview_supporters
  get "checkout/:ids", to:"product#index",constraints: { ids: /hotsale_\S+/ },as: :hotsale_index
  get 'checkout/:procamp', to: 'shop#product_weixin',constraints: { procamp: /procamp_\S+_[0-9]+/ }, as: :shop_product_weixin_pay
  get "checkout/:partyid", to:"shop_mall#party_index",constraints: { partyid: /party_\S+/ },as: :party_index_weixin
  get 'checkout/shgs', to: 'campaign_ngo#shgs', as: :campagin_ngo_shgs
  get 'campaginngo/shgs_supporters', to: 'campaign_ngo#shgs_supporters', as: :campagin_ngo_shgs_supporters

  get 'checkout/xyetjk', to: 'campaign_ngo#xyetjk', as: :campagin_ngo_xyetjk
  get 'campaginngo/xyetjk_supporters', to: 'campaign_ngo#xyetjk_supporters', as: :campagin_ngo_xyetjk_supporters

  get 'checkout/lbxgy', to: 'campaign_ngo#lbxgy', as: :campagin_ngo_lbxgy
  get 'campaginngo/lbxgy_supporters', to: 'campaign_ngo#lbxgy_supporters', as: :campagin_ngo_lbxgy_supporters

  get 'checkout/lbflower', to: 'campaign_ngo#lbflower', as: :campagin_ngo_lbflower
  get 'campaginngo/lbflower_supporters', to: 'campaign_ngo#lbflower_supporters', as: :campagin_ngo_lbflower_supporters

  get 'checkout/lbpulushi', to: 'campaign_ngo#lbpulushi', as: :campaign_ngo_lbpulushi
  get 'campaginngo/lbpulushi_supporters', to: 'campaign_ngo#lbpulushi_supporters', as: :campagin_ngo_lbpulushi_supporters
  
  post 'campaginngo/confirmation', to: 'campaign_ngo#confirmation', as: :campaign_ngo_checkout_confirmation
  post 'campaginngo/confirmation_weixin', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin
  post 'campaginngo/confirmation_weixin/:campaign_id', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin_bycampaign

app/controllers/admin/mall_controller.rb
class Admin::MallController < Admin::ApplicationController
  def settings
    @root_categories = ProductCategory.showroot.order(:sort_mark)
    @all_products = Product.isnot_destroy.order(:id=>:desc)
    @top_categories = MallTopCategory.all
    @slider_images = MallSliderImage.order(:sort_order).all
    @hot_products = MallHotProduct.all
  end
  
  def save_settings
    MallTopCategory.all.each do |c|
      c.delete
    end
    
    MallSliderImage.all.each do |i|
      i.delete
    end
    
    MallHotProduct.all.each do |p|
      p.delete
    end
    
    if params[:top_pc].present?
      params[:top_pc].each_with_index { |pc, idx| 
        MallTopCategory.create product_category_id: pc, sort_order: params["top_pc_order_" + pc].to_i
      }
    end
    
    if params[:hot_prod].present?
      params[:hot_prod].each_with_index { |hp, idx| 
        MallHotProduct.create product_id: hp, sort_order: (params["hot_prod_order_" + hp] || "999").to_i
      }
    end
    
    if params[:slider_images].present?
      params[:slider_images].each do |si|
        begin
          img_hash = JSON.parse(si)
          
          MallSliderImage.create public_id: img_hash["public_id"], image_url: img_hash["secure_url"],
            image_width: img_hash["image_width"], image_height: img_hash["image_height"], 
            sort_order: img_hash["sort_order"].to_i,
            crop_x: img_hash["crop_x"], crop_y: img_hash["crop_y"], crop_width: img_hash["crop_width"],
            crop_height: img_hash["crop_height"], is_cropped: true, target_url: img_hash["target_url"]
        rescue
        end
      end
    end
    
    redirect_to admin_mall_settings_path and return
  end
end

app/controllers/mall_controller.rb
class MallController < ApplicationController
  layout "mall"
  
  before_filter :load_mall, only: [:home, :search, :search_page, :orders, :order_detail]
  before_filter :manage_session_order, only: [:home, :search, :search_page, :orders, :order_detail]
  
  def home
    @products = []
    
    MallHotProduct.order(:sort_order).each do |hp|
      if @products.count >= 6
        break
      end
      
      @products << hp.product if !hp.product.is_destroy
    end
    
    @top_categories = []
    
    MallTopCategory.order(:sort_order).each do |tc|
      if @top_categories.count >= 4
        break
      end
      
      @top_categories << tc.product_category if tc.product_category.active && !tc.product_category.is_destroy
    end
    
    @slider_images = MallSliderImage.order(:sort_order)
  end
  
  def search
    do_search
  end
  
  def search_page
    do_search
    
    render partial: "mall/pager/search" and return
  end
  
  def orders
    do_orders
  end
  
  def orders_page
    do_orders
    
    render partial: "mall/pager/orders" and return
  end
  
  def order_detail
    @the_order = Order.where(:open_id => session[:openid] || "", :id => params[:id].to_i).first
    @items_express=Hash.new
    @the_order.items.each do |item|
      if item.courier_number&&item.courier_number.length>0
        @items_express[item.courier_number]=item
      end
    end
    if !@the_order
      redirect_to mall_home_path and return
    end
  end
  
  private
  
  def load_mall
    @campaign = Campaign.find_by_id(0)
    @root_categories = ProductCategory.showroot.order(:sort_mark)
  end
  
  def manage_session_order
    @order = Order.find_by_id(session[:order_id])
    
    unless @order && @order.campaign_id == @campaign.id && @order.status == 0
      @order = Order.new
    end
  end
  
  def do_orders
    @page = params[:page].to_i
    @page = 1 if @page == 0
    @show_pager = false
    @orders = Order.where(open_id: session[:openid] || "").completed.order(:id=>:desc).page(@page).per(5)
    
    if @orders.total_pages > 0 && @orders.total_pages > @page
      @show_pager = true
      
      query = "?" + {:page => @page + 1}.map{|k,v| "#{k}=#{CGI::escape(v.to_s)}"}.join("&")
      
      @page_url = mall_orders_page_path + query
    end
  end
  
  def do_search
    @products = Product.isnot_destroy
    
    if params[:mall_search_text].present?
      tag_prod_ids = Tag.isnot_destroy.is_active.joins(:products).where(
        "tags.name ilike :search", search: '%' + params[:mall_search_text] + '%').select(
        "products.id as prod_id").collect(&:prod_id).uniq
      
      if tag_prod_ids.count > 0
        @products = @products.where("name ilike :search or id in (:tag_prod_ids)", 
          search: '%' + params[:mall_search_text] + '%', tag_prod_ids: tag_prod_ids)
      else
        @products = @products.where("name ilike :search", search: '%' + params[:mall_search_text] + '%')
      end
    end
    
    if params[:category_id].present?
      @products = @products.where(:product_category_id => params[:category_id].to_i)
    end
    
    if params[:subcategory_id].present?
      @products = @products.where(:pro_cat_subclass_id => params[:subcategory_id].to_i)
    end
    
    @page = params[:page].to_i
    @page = 1 if @page == 0
    @show_pager = false
    @products = @products.order(:id => :desc).page(@page).per(5)
    
    if @products.total_pages > 0 && @products.total_pages > @page
      @show_pager = true
      
      query = "?" + {:page => @page + 1,
        :mall_search_text => params[:mall_search_text] || "",
        :category_id => params[:category_id] || "",
        :subcategory_id => params[:subcategory_id] || ""}.map{|k,v| "#{k}=#{CGI::escape(v.to_s)}"}.join("&")
      
      @page_url = mall_search_page_path + query
    end
  end
end

app/views/mall/pager/_orders.html.erb
<% if @orders && @orders.count > 0 %>
    <% @orders.each do |order| %>
        <div class="order_content order_item" data-url="<%= mall_order_detail_path order.id %>">
          <p style="width:120px; text-align:center;">
						<% if order.campaign.used_as_default? %>
							<% if order.items.first.product.picture %>
                <%= cl_image_tag order.items.first.product.picture, style: "max-width:120px; max-height:100px;" %>
							<% else %>
								<%= image_tag 'crown.png', style: "width:120px;" %>
							<% end %>
						<% else %>
              <% if order.campaign.campaign_logo %>
                  <%= cl_image_tag order.campaign.campaign_logo.image_id,
                                   transformation: [
                                           {
                                                   width: order.campaign.campaign_logo.crop_width,
                                                   height: order.campaign.campaign_logo.crop_height,
                                                   x: order.campaign.campaign_logo.crop_x,
                                                   y: order.campaign.campaign_logo.crop_y,
                                                   crop: :crop
                                           }
                                   ], style: "max-width:120px; max-height:100px;" %>
              <% else %>
                  <%= image_tag 'crown.png', style: "width:120px;" %>
              <% end %>
						<% end %>
          </p>

          <div class="right_content">
            <div class="title" style="font-size:16px; max-height:44px; overflow:hidden;">
              <%= order.campaign.used_as_default? ? order.items.first.product.name : order.campaign.title %>
            </div>
            <div class="detail" style="margin-top:5px;">
              <div>
                <%= order.num_items %>件｜总价：￥<%= long_price(order.grandtotal.to_f/100) %>
              </div>
              <div>
                已付款
              </div>
            </div>
          </div>
          <input class="order_id" type="hidden" value="<%= order.id %>"/>
        </div>
    <% end %>
		
		<% if @show_pager %>
		<div style="text-align:center; padding:20px 0px 30px 0px;">
			<a href="<%= @page_url %>" class="a-pager" style="color:#333; font-size:14px; text-decoration:underline;">查看更多</a>
		</div>
		<% end %>
<% else %>
		<div style="color:#999; font-size:16px; margin-top:40px; text-align:center;">
			<strong>您还没有任何订单</strong>
		</div>
<% end %>

app/views/mall/pager/_search.html.erb
<% @products.each do |product| %>
<div class="row">
	<div class="col-xs-6" style="padding:0px 5px; text-align:center;">
		<a href="<%= shop_product_path(@campaign, product) %>">
			<%= cl_image_tag product.picture, style: "max-width:100%; max-height:150px;" %>
		</a>
	</div>
	<div class="col-xs-6" style="padding:0px 5px;">
		<div style="font-size:16px; text-align:center; max-height:44px; overflow:hidden;">
			<a href="<%= shop_product_path(@campaign, product) %>" style="color:#333;">
				<strong><%= product.name %></strong>
			</a>
		</div>
		
		<% price_range=product.price_range(1) %>
		
		<div style="font-size:14px; text-align:center; margin-top:10px;">
			<% if price_range[:is_discount] %>
				<span style="color:gray; display:inline-block; text-decoration:line-through;">
					<% if price_range[:same_price] %>
					￥<%= long_price(price_range[:min]) %>
				<% else %>
					￥<%= long_price(price_range[:min]) %> - <%= long_price(price_range[:max]) %>
				<% end %></span><br/>
				<span style="color:rgb(210, 16, 16); display:inline-block;">
				<% if price_range[:same_discount_price] %>
					￥<%= long_price(price_range[:discount_min]) %>
				<% else %>
					￥<%= long_price(price_range[:discount_min]) %> - <%= long_price(price_range[:discount_max]) %>
				<% end %>
				</span>
			<% else %>
				<% if price_range[:same_price] %>
					￥<%= long_price(price_range[:min]) %>
				<% else %>
					￥<%= long_price(price_range[:min]) %> - <%= long_price(price_range[:max]) %>
				<% end %>
			<% end %>
		
			<div style="margin-top:10px; text-align:center;">
				<a href="<%= shop_product_path(@campaign, product) %>" class="btn btn-primary" style="width:100px;"><span class="text">立即购买</span></a>
			</div>
		</div>
	</div>
</div>
<hr/>
<% end %>

<% if @show_pager %>
<div style="text-align:center; padding:0px 0px 30px 0px;">
	<a href="<%= @page_url %>" class="a-pager" style="color:#333; font-size:14px; text-decoration:underline;">查看更多</a>
</div>
<% end %>