config/routes.rb
Raisy::Application.routes.draw do
  
  mount WeixinRailsMiddleware::Engine, at: "/"
    # root 'pages#index'
    root 'fancy#index'
    
    devise_for :users,:controllers => {:registrations => "registrations"}
    
    devise_scope :user do 
      get 'signup_social_user', to: 'registrations#signup_social_user'
    end
    
    get "/auth/failure", to: "users#omniauth_failure"
    get "/auth/twitter/callback", to: "users#omniauth_callback"
    get "/auth/facebook/callback", to: "users#omniauth_callback"
    
    match "/user/verify" => "users#verify_user", via: [:get, :post]
    match "/user/lookup" => "users#lookup_user", via: [:get, :post]

    namespace :admin do
        root 'dashboard#index'
        
        resources :collections do
            resources :categories
        end

        resources :product_categories do
          match 'product_categories/new', to: 'product_categories#subclassnew',via:[:get], as: :new_product_category_subclass
          post 'product_categories', to: 'product_categories#subclasscreate', as: :create_product_category_subclass
          get 'product_categories', to: 'product_categories#subclassindex', as: :index_product_category_subclass
          delete 'product_categories/:id', to: 'product_categories#subclassdestroy', as: :delete_product_category_subclass
          get  'product_categories/:id/edit', to: 'product_categories#subclassedit', as: :edit_product_category_subclass
          get  'product_categories/:id', to: 'product_categories#subclassshow', as: :show_product_category_subclass
          match  'product_categories/:id', to: 'product_categories#subclassupdate',via: [:patch,:put], as: :update_product_category_subclass

          get  'product_categories/ajax/select', to: 'product_categories#sublass_ajax_select', as: :show_product_category_subclass_ajax_select
          resources :product_categories
        end

        get 'products/ajax',to: 'products#show_pager_data', as: :load_products_show_pager_data
        post 'products/ajax',to: 'products#show_pager_data', as: :products_show_pager_data
        resources :products do
          get '/option_group/edit', to: 'products#edit_option_group', as: :edit_option_group
          match '/option_group/save' => 'products#save_option_group', via: [:post, :patch], as: :save_option_group
          delete '/option_group/delete', to: 'products#delete_option_group', as: :delete_option_group
          post '/option_group_property/:id/save', to: 'products#save_option_group_property', as: :save_option_group_property
          delete '/option_group_property/:id/delete', to: 'products#delete_option_group_property', as: :delete_option_group_property
        end
        
        resources :invites
        resources :organizations
        post 'organizations/ajax',to: 'organizations#ajax_pager_data', as: :organizations_page_ajax
        resources :users
        
        resources :campaigns do
            resources :orders
        end
        post 'campaigns/ajax',to: 'campaigns#ajax_pager_data', as: :campaigns_page_ajax
        
        resources :settings
        resources :vendors

        resources :tags
        post 'tags/ajax',to: 'tags#ajax_pager_data', as: :tags_page_ajax
        post  'tags/search_ajax',to:"tags#search_ajax", as: :tags_search_ajax
        post  'tags/ajax_delete',to: 'tags#ajax_delete', as: :tags_ajax_delete
        
        get 'campaign_stories', to: 'campaigns#stories'
        get 'campaign_story/:id', to: 'campaigns#story'
        post 'campaign_save_story', to: 'campaigns#save_story'
        
        get 'campaign_images', to: 'campaigns#images'
        get 'campaign_image', to: 'campaigns#image'
        get 'campaign_delete_image', to: 'campaigns#delete_image'
        post 'campaign_save_image', to: 'campaigns#save_image'
        
        get 'default_email_message', to: 'settings#default_email_message'
        post 'save_default_email_message', to: 'settings#save_default_email_message'
        get 'default_chairperson_email_message', to: 'settings#default_chairperson_email_message'
        post 'save_default_chairperson_email_message', to: 'settings#save_default_chairperson_email_message'
        
        get 'campaign_bulkshippinginfo/:id', to: 'campaigns#bulkshippinginfo', as: :campaign_bulkshippinginfo
        post 'campaign_bulkshippinginfo/:id/create', to: 'campaigns#create_bulkshippinginfo', as: :campaign_bulkshippinginfos
        patch 'campaign_bulkshippinginfo/:id', to: 'campaigns#update_bulkshippinginfo'
        
        get 'product_collections/:id', to: 'products#prod_collections', as: :product_collections
        
        namespace :reports do
          root 'reportsboard#index'
          get 'campvisit_log/report',to: 'campaign_visit_log#reportindex', as: :campvisit_log_report
          post 'campvisit_log/report',to: 'campaign_visit_log#reportsearch', as: :campvisit_log_report_search
          get 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation', as: :campvisit_log_report_visit_share_donation
          post 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation_ajax', as: :ajax_campvisit_log_report_visit_share_donation
          get 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log', as: :campvisit_log_report_visit_log
          post 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log_ajax', as: :ajax_campvisit_log_report_visit_log
        end
        
        resources :questionnaires
      
        get 'mall_settings', to: 'mall#settings', as: :mall_settings
        post 'save_mall_settings', to: 'mall#save_settings', as: :save_mall_settings

        resources :express_upload
        get 'express/load_excle',to: 'express_upload#load_excle',as: :express_load_excle_ajax
        get 'express/validate',to: 'express_upload#validate_check',as: :express_validate_ajax
        get 'express/update',to: 'express_upload#update_data',as: :express_update_ajax
        get 'express/donload',to: 'express_upload#donload',as: :express_donload
        
        get 'weishop_settings', to: 'weishop#settings', as: :weishop_settings
        post 'save_weishop_settings', to: 'weishop#save_settings', as: :save_weishop_settings
        
    end

  #Express
  get 'order_express/:item_id/:courier_number', to: 'express#order_express', as: :order_express
  get 'order_express_ajax/:item_id/:courier_number', to: 'express#order_express_ajax', as: :order_express_ajax
  get 'order_express_ajax', to: 'express#order_express_ajax', as: :order_express_ajax_get


    # Mall
    scope 'mall' do
      root 'mall#home', as: :mall_home
      match 'search' => 'mall#search', via: [:get, :post], as: :mall_search
      match 'search_page' => 'mall#search_page', via: [:get, :post], as: :mall_search_page
      get 'orders', to: 'mall#orders', as: :mall_orders
      get 'orders_page', to: 'mall#orders_page', as: :mall_orders_page
      get 'order_detail/:id', to: 'mall#order_detail', as: :mall_order_detail
    end

    resources :collections
    resources :organizations


  get 'shopmall/product/:product_id', to: 'shop_mall#product', as: :shop_mall_product
  get 'shopmall/pay', to: 'shop_mall#pay', as: :shop_mall_product_pay
  # get 'shopmall/product_id', to: 'shop_mall#product', as: :shop_mall_product_view
    #personal_story
  get 'checkout/lzds', to: 'campaign_ngo#lzds', as: :campagin_ngo_lzds
  get 'campaginngo/lzds_supporters', to: 'campaign_ngo#lzds_supporters', as: :campagin_ngo_lzds_supporters

  get 'checkout/lovehb', to: 'campaign_ngo#lovehb', as: :campagin_ngo_lovehb
  get 'campaginngo/lovehb_supporters', to: 'campaign_ngo#lovehb_supporters', as: :campagin_ngo_lovehb_supporters

  get 'checkout/xgst', to: 'campaign_ngo#xgst', as: :campagin_ngo_xgst
  get 'campaginngo/xgst_supporters', to: 'campaign_ngo#xgst_supporters', as: :campagin_ngo_xgst_supporters

  get 'checkout/:id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview_checkout
  get ':id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview
  get 'campaginngo/campaignview_supporters', to: 'campaign_ngo#campaignview_supporters', as: :campagin_ngo_campaignview_supporters
  get "checkout/:ids", to:"product#index",constraints: { ids: /hotsale_\S+/ },as: :hotsale_index
  get 'checkout/:procamp', to: 'shop#product_weixin',constraints: { procamp: /procamp_\S+_[0-9]+/ }, as: :shop_product_weixin_pay
  get "checkout/:partyid", to:"shop_mall#party_index",constraints: { partyid: /party_\S+/ },as: :party_index_weixin
  get 'checkout/shgs', to: 'campaign_ngo#shgs', as: :campagin_ngo_shgs
  get 'campaginngo/shgs_supporters', to: 'campaign_ngo#shgs_supporters', as: :campagin_ngo_shgs_supporters

  get 'checkout/xyetjk', to: 'campaign_ngo#xyetjk', as: :campagin_ngo_xyetjk
  get 'campaginngo/xyetjk_supporters', to: 'campaign_ngo#xyetjk_supporters', as: :campagin_ngo_xyetjk_supporters

  get 'checkout/lbxgy', to: 'campaign_ngo#lbxgy', as: :campagin_ngo_lbxgy
  get 'campaginngo/lbxgy_supporters', to: 'campaign_ngo#lbxgy_supporters', as: :campagin_ngo_lbxgy_supporters

  get 'checkout/lbflower', to: 'campaign_ngo#lbflower', as: :campagin_ngo_lbflower
  get 'campaginngo/lbflower_supporters', to: 'campaign_ngo#lbflower_supporters', as: :campagin_ngo_lbflower_supporters

  get 'checkout/lbpulushi', to: 'campaign_ngo#lbpulushi', as: :campaign_ngo_lbpulushi
  get 'campaginngo/lbpulushi_supporters', to: 'campaign_ngo#lbpulushi_supporters', as: :campagin_ngo_lbpulushi_supporters
  
  post 'campaginngo/confirmation', to: 'campaign_ngo#confirmation', as: :campaign_ngo_checkout_confirmation
  post 'campaginngo/confirmation_weixin', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin
  post 'campaginngo/confirmation_weixin/:campaign_id', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin_bycampaign

app/models/organization.rb
class Organization < ActiveRecord::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged

    # Try building a slug based on the following fields in
    # increasing order of specificity.
    def slug_candidates
        [
            :name,
            [:name, "#{Organization.where(name: name).count + 1}"]
        ]
    end
    
    belongs_to :country
    belongs_to :state_province
    
    validates :name, presence: true
    paginates_per 10
    scope :active, -> { where(:deleted=>false) }

    has_many :organization_roles
    #has_many :users, -> { distinct }, through: :organization_roles
    has_and_belongs_to_many :users
    has_many :campaigns, -> { where(:is_destroy=>false) }

    has_many :questionnaires

    def has_rep?
        self.legal_rep_first_name.present? && self.legal_rep_last_name.present? && self.legal_rep_phone.present?
    end

    def has_bank?
        self.routing_number.present? && self.account_number.present?
    end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::ApplicationController
  before_filter :load_organization, only: [:edit, :update, :destroy]
  before_filter :load_countries_states, only: [:new, :create, :edit, :update]
  before_filter :load_campaign, only: [:edit, :update]
  
  def index
    @organizations = Organization.active.order(:id)
  end

  def ajax_pager_data
    @organizations=Organization.active.order(:updated_at => :desc).page(params[:page]).per(Kaminari.config.default_per_page);

    render partial: "table_show"
  end

  def new
     @organization = Organization.new
  end
  
  def create
    @organization = Organization.new
    
    @organization.assign_attributes(organization_params)
    @organization.entertainment_customer_id = Time.now.to_i.to_s
    
    if !@organization.valid?
        message = ''
        @organization.errors.each do |key, error|
            message = message + key.to_s.humanize + ' ' + error.to_s + ', '
        end
        flash.now[:danger] = message[0...-2]
        render action: "new" and return
    end
    
    @organization.save
    
    redirect_to admin_organizations_path, flash: { success: "组织已创建" }
  end
  
  def edit
    
  end
  
  def update
    @organization.assign_attributes(organization_params)
    
    if !@organization.valid?
        message = ''
        @organization.errors.each do |key, error|
            message = message + key.to_s.humanize + ' ' + error.to_s + ', '
        end
        flash.now[:danger] = message[0...-2]
        render action: "edit" and return
    end
    
    @organization.save
    
    redirect_to admin_organizations_path, flash: { success: "组织已更新" }
  end
  
  def destroy
    @organization.deleted=true
    @organization.save

    @organization.campaigns.each do |cap|
      cap.update(is_destroy:true)
    end

    campaign = Campaign.where(:organization_id=>@organization.id, :campaign_type=>2).first
    
    if campaign
      campaign.active = false
      campaign.save
    end
    
    redirect_to admin_organizations_path, flash: { success: "组织已删除" }
  end
  
  private
  
  def organization_params
      params.require(:organization).permit :name, :address_line_one, :address_line_two, :address_city,
      :state_province_id, :address_postal_code, :country_id
  end
  
  def load_organization
    begin
      @organization = Organization.friendly.find(params[:id])
    rescue
      redirect_to admin_root_path and return
    end
  end
  
  def load_countries_states
    @countries = Country.order(:id)
    @state_provinces = StateProvince.order(:id)
  end
  
  def load_campaign
    @campaign = Campaign.where(organization_id: @organization.id, campaign_type: 2).first
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

    def update_details
        @organization = Organization.friendly.find(params[:id])
        @organization.assign_attributes organization_params

        # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
        if !@organization.valid?
            message = ''
            @organization.errors.each do |key, error|
                message = message + key.to_s.humanize + ' ' + error.to_s + ', '
            end
            flash.now[:danger] = message[0...-2]
            render 'chairperson_dashboard/organization_details' and return
        end

        @organization.save

        if params[:organization_logo].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:organization_logo])
            if preloaded.valid?
                @organization.update_attribute(:logo, preloaded.identifier)
            end
        end

        redirect_to(dashboard_organization_details_url(@organization), flash: { success: "保存成功" }) and return
    end

    def update_deposit
        @organization = Organization.friendly.find(params[:id])
        @organization.assign_attributes organization_deposit_params

        # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
        if !@organization.valid?
            message = ''
            @organization.errors.each do |key, error|
                message = message + key.to_s.humanize + ' ' + error.to_s + ', '
            end
            flash.now[:danger] = message[0...-2]
            render 'chairperson_dashboard/organization_deposit' and return
        end

        @organization.save

        redirect_to(dashboard_organization_deposit_url(@organization), flash: { success: "Deposit information updated!" }) and return
    end

    private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def organization_params
        params.require(:organization).permit :name, :address_line_one, :address_line_two, :address_city, :address_state, :address_postal_code, :phone,
                                                                  :email, :website
    end

    def organization_deposit_params
        params.require(:organization).permit :legal_name, :legal_tax_id, :legal_address_line_one, :legal_address_line_two, :legal_address_city,
                                                                  :legal_address_state, :legal_address_postal_code, :legal_rep_first_name, :legal_rep_last_name, :legal_rep_dob,
                                                                  :legal_rep_tax_id, :legal_rep_phone, :legal_rep_email, :account_number, :routing_number
    end

end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/organizations/_form.html.erb
<script>
  var state_provinces = [];
  var country_id =<%= @organization.country_id.blank? ? 0 : @organization.country_id%>;
  var state_province_id =<%= @organization.state_province_id.blank? ? 0 : @organization.state_province_id%>;

  <% @state_provinces.each do |state_province| %>
  state_provinces.push({
    id:<%=state_province.id%>,
    name: "<%=state_province.name%>",
    country_id: <%=state_province.country_id%>
  });
  <% end %>
</script>

<%= form_for([:admin, @organization], html: {id: "organization_form", class: "organization_form"}) do |f| %>
    <fieldset>
      <div class="row">
        <div class="col-md-12">
          <div class="well">
            <% if f.object.id.present? %>
                <div class="row">
                  <div class="col-md-12 form-group">
                    <label for="product_name">组织代码</label>
                    <%= f.object.entertainment_customer_id %>
                  </div>
                </div>
            <% end %>

            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_name">名称</label>
                <!-- Make organization an input by add class .input-organization -->
                <%= f.text_field :name, class: 'form-control input-organization' %>
              </div>
            </div>
          </div>

          <div class="well">
            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_address_line_one">地址1</label>
                <%= f.text_field :address_line_one, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_address_line_two">地址2</label>
                <%= f.text_field :address_line_two, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_address_city">城市</label>
                <%= f.text_field :address_city, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_address_postal_code">邮政编码</label>
                <%= f.text_field :address_postal_code, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_address_country">国家</label>
                <select id="organization_address_country" name="organization[country_id]" class="form-control input-small" style="width:200px">
                  <option value="">-- 请选择 --</option>
                  <% @countries.each do |country| %>
                      <option value="<%= country.id %>" <%= f.object.country_id == country.id ? 'selected' : '' %> >
                        <%= country.name %>
                      </option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 form-group">
                <label for="organization_address_state">省/市</label>
                <select id="organization_address_state" name="organization[state_province_id]" class="form-control input-small">
                </select>
              </div>
            </div>
          </div>

          <% if f.object.id.present? %>
              <div class="well">
                <% if @campaign %>
                    <%= link_to '编辑筹款页面', edit_admin_campaign_path(@campaign) + "?organization=" + f.object.id.to_s %>
                <% else %>
                    <%= link_to '编辑筹款页面', new_admin_campaign_path + "?organization=" + f.object.id.to_s %>
                <% end %>


              </div>
              <div class="well">
                <%= link_to "合作意向调查表", new_admin_questionnaire_path+"?organization=" + f.object.id.to_s %>
              </div>
          <% end %>
        </div>
      </div>

      <div>
        <button class="btn btn-primary btn-lg" type="submit">
          <span class="text">保存</span>
        </button>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "返回", admin_organizations_path, class: "btn btn-primary btn-lg" %>
      </div>
    </fieldset>
<% end %>

app/views/admin/organizations/_table_show.html.erb
<table class="table table-hover" style="">
  <thead>
  <tr>
    <th>日期</th>
    <th>名称</th>
    <th>组织代码</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.created_at.strftime('%b %-d, %Y') %></td>
        <td><%= link_to organization.name, edit_admin_organization_path(organization) %></td>
        <td><%= organization.entertainment_customer_id %></td>
        <td><%= link_to "删除", admin_organization_path(organization), method: :delete, data: {
            confirm: "您确定要删除该组织吗?" } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div id="page_pager" style="text-align:center;"><%= paginate @organizations if @organizations %></div>

app/views/admin/organizations/edit.html.erb
<div id="organization" style="padding: 30px 0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>编辑: <%= @organization.name %></h3>
            </div>
        </div>
		
        <div class="row">
            <div class="col-md-12">
				<%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/admin/organizations/new.html.erb
<div id="organization" style="padding: 30px 0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>新组织</h3>
            </div>
        </div>
		
        <div class="row">
            <div class="col-md-12">
				<%= render 'form' %>
            </div>
        </div>
    </div>
</div>