config/routes.rb
Raisy::Application.routes.draw do
  
  mount WeixinRailsMiddleware::Engine, at: "/"
    # root 'pages#index'
    root 'fancy#index'
    
    devise_for :users,:controllers => {:registrations => "registrations"}
    
    devise_scope :user do 
      get 'signup_social_user', to: 'registrations#signup_social_user'
    end
    
    get "/auth/failure", to: "users#omniauth_failure"
    get "/auth/twitter/callback", to: "users#omniauth_callback"
    get "/auth/facebook/callback", to: "users#omniauth_callback"
    
    match "/user/verify" => "users#verify_user", via: [:get, :post]
    match "/user/lookup" => "users#lookup_user", via: [:get, :post]

    namespace :admin do
        root 'dashboard#index'
        
        resources :collections do
            resources :categories
        end

        resources :product_categories do
          match 'product_categories/new', to: 'product_categories#subclassnew',via:[:get], as: :new_product_category_subclass
          post 'product_categories', to: 'product_categories#subclasscreate', as: :create_product_category_subclass
          get 'product_categories', to: 'product_categories#subclassindex', as: :index_product_category_subclass
          delete 'product_categories/:id', to: 'product_categories#subclassdestroy', as: :delete_product_category_subclass
          get  'product_categories/:id/edit', to: 'product_categories#subclassedit', as: :edit_product_category_subclass
          get  'product_categories/:id', to: 'product_categories#subclassshow', as: :show_product_category_subclass
          match  'product_categories/:id', to: 'product_categories#subclassupdate',via: [:patch,:put], as: :update_product_category_subclass

          get  'product_categories/ajax/select', to: 'product_categories#sublass_ajax_select', as: :show_product_category_subclass_ajax_select
          resources :product_categories
        end

        get 'products/ajax',to: 'products#show_pager_data', as: :load_products_show_pager_data
        post 'products/ajax',to: 'products#show_pager_data', as: :products_show_pager_data
        resources :products do
          get '/option_group/edit', to: 'products#edit_option_group', as: :edit_option_group
          match '/option_group/save' => 'products#save_option_group', via: [:post, :patch], as: :save_option_group
          delete '/option_group/delete', to: 'products#delete_option_group', as: :delete_option_group
          post '/option_group_property/:id/save', to: 'products#save_option_group_property', as: :save_option_group_property
          delete '/option_group_property/:id/delete', to: 'products#delete_option_group_property', as: :delete_option_group_property
        end
        
        resources :invites
        resources :organizations
        post 'organizations/ajax',to: 'organizations#ajax_pager_data', as: :organizations_page_ajax
        resources :users
        
        resources :campaigns do
            resources :orders
        end
        post 'campaigns/ajax',to: 'campaigns#ajax_pager_data', as: :campaigns_page_ajax
        
        resources :settings
        resources :vendors

        resources :tags
        post 'tags/ajax',to: 'tags#ajax_pager_data', as: :tags_page_ajax
        post  'tags/search_ajax',to:"tags#search_ajax", as: :tags_search_ajax
        post  'tags/ajax_delete',to: 'tags#ajax_delete', as: :tags_ajax_delete
        
        get 'campaign_stories', to: 'campaigns#stories'
        get 'campaign_story/:id', to: 'campaigns#story'
        post 'campaign_save_story', to: 'campaigns#save_story'
        
        get 'campaign_images', to: 'campaigns#images'
        get 'campaign_image', to: 'campaigns#image'
        get 'campaign_delete_image', to: 'campaigns#delete_image'
        post 'campaign_save_image', to: 'campaigns#save_image'
        
        get 'default_email_message', to: 'settings#default_email_message'
        post 'save_default_email_message', to: 'settings#save_default_email_message'
        get 'default_chairperson_email_message', to: 'settings#default_chairperson_email_message'
        post 'save_default_chairperson_email_message', to: 'settings#save_default_chairperson_email_message'
        
        get 'campaign_bulkshippinginfo/:id', to: 'campaigns#bulkshippinginfo', as: :campaign_bulkshippinginfo
        post 'campaign_bulkshippinginfo/:id/create', to: 'campaigns#create_bulkshippinginfo', as: :campaign_bulkshippinginfos
        patch 'campaign_bulkshippinginfo/:id', to: 'campaigns#update_bulkshippinginfo'
        
        get 'product_collections/:id', to: 'products#prod_collections', as: :product_collections
        
        namespace :reports do
          root 'reportsboard#index'
          get 'campvisit_log/report',to: 'campaign_visit_log#reportindex', as: :campvisit_log_report
          post 'campvisit_log/report',to: 'campaign_visit_log#reportsearch', as: :campvisit_log_report_search
          get 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation', as: :campvisit_log_report_visit_share_donation
          post 'campvisit_log/report_visit_share_donation',to: 'campaign_visit_log#visit_share_donation_ajax', as: :ajax_campvisit_log_report_visit_share_donation
          get 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log', as: :campvisit_log_report_visit_log
          post 'campvisit_log/report_visit_log',to: 'campaign_visit_log#report_visit_log_ajax', as: :ajax_campvisit_log_report_visit_log
        end
        
        resources :questionnaires
      
        get 'mall_settings', to: 'mall#settings', as: :mall_settings
        post 'save_mall_settings', to: 'mall#save_settings', as: :save_mall_settings

        resources :express_upload
        get 'express/load_excle',to: 'express_upload#load_excle',as: :express_load_excle_ajax
        get 'express/validate',to: 'express_upload#validate_check',as: :express_validate_ajax
        get 'express/update',to: 'express_upload#update_data',as: :express_update_ajax
        get 'express/donload',to: 'express_upload#donload',as: :express_donload
        
        get 'weishop_settings', to: 'weishop#settings', as: :weishop_settings
        post 'save_weishop_settings', to: 'weishop#save_settings', as: :save_weishop_settings
        
    end

  #Express
  get 'order_express/:item_id/:courier_number', to: 'express#order_express', as: :order_express
  get 'order_express_ajax/:item_id/:courier_number', to: 'express#order_express_ajax', as: :order_express_ajax
  get 'order_express_ajax', to: 'express#order_express_ajax', as: :order_express_ajax_get


    # Mall
    scope 'mall' do
      root 'mall#home', as: :mall_home
      match 'search' => 'mall#search', via: [:get, :post], as: :mall_search
      match 'search_page' => 'mall#search_page', via: [:get, :post], as: :mall_search_page
      get 'orders', to: 'mall#orders', as: :mall_orders
      get 'orders_page', to: 'mall#orders_page', as: :mall_orders_page
      get 'order_detail/:id', to: 'mall#order_detail', as: :mall_order_detail
    end

    resources :collections
    resources :organizations


  get 'shopmall/product/:product_id', to: 'shop_mall#product', as: :shop_mall_product
  get 'shopmall/pay', to: 'shop_mall#pay', as: :shop_mall_product_pay
  # get 'shopmall/product_id', to: 'shop_mall#product', as: :shop_mall_product_view
    #personal_story
  get 'checkout/lzds', to: 'campaign_ngo#lzds', as: :campagin_ngo_lzds
  get 'campaginngo/lzds_supporters', to: 'campaign_ngo#lzds_supporters', as: :campagin_ngo_lzds_supporters

  get 'checkout/lovehb', to: 'campaign_ngo#lovehb', as: :campagin_ngo_lovehb
  get 'campaginngo/lovehb_supporters', to: 'campaign_ngo#lovehb_supporters', as: :campagin_ngo_lovehb_supporters

  get 'checkout/xgst', to: 'campaign_ngo#xgst', as: :campagin_ngo_xgst
  get 'campaginngo/xgst_supporters', to: 'campaign_ngo#xgst_supporters', as: :campagin_ngo_xgst_supporters

  get 'checkout/:id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview_checkout
  get ':id', to: 'campaign_ngo#campaignview',constraints: { id: /campaign_[0-9]*/ }, as: :campagin_ngo_campaignview
  get 'campaginngo/campaignview_supporters', to: 'campaign_ngo#campaignview_supporters', as: :campagin_ngo_campaignview_supporters
  get "checkout/:ids", to:"product#index",constraints: { ids: /hotsale_\S+/ },as: :hotsale_index
  get 'checkout/:procamp', to: 'shop#product_weixin',constraints: { procamp: /procamp_\S+_[0-9]+/ }, as: :shop_product_weixin_pay
  get "checkout/:partyid", to:"shop_mall#party_index",constraints: { partyid: /party_\S+/ },as: :party_index_weixin
  get 'checkout/shgs', to: 'campaign_ngo#shgs', as: :campagin_ngo_shgs
  get 'campaginngo/shgs_supporters', to: 'campaign_ngo#shgs_supporters', as: :campagin_ngo_shgs_supporters

  get 'checkout/xyetjk', to: 'campaign_ngo#xyetjk', as: :campagin_ngo_xyetjk
  get 'campaginngo/xyetjk_supporters', to: 'campaign_ngo#xyetjk_supporters', as: :campagin_ngo_xyetjk_supporters

  get 'checkout/lbxgy', to: 'campaign_ngo#lbxgy', as: :campagin_ngo_lbxgy
  get 'campaginngo/lbxgy_supporters', to: 'campaign_ngo#lbxgy_supporters', as: :campagin_ngo_lbxgy_supporters

  get 'checkout/lbflower', to: 'campaign_ngo#lbflower', as: :campagin_ngo_lbflower
  get 'campaginngo/lbflower_supporters', to: 'campaign_ngo#lbflower_supporters', as: :campagin_ngo_lbflower_supporters

  get 'checkout/lbpulushi', to: 'campaign_ngo#lbpulushi', as: :campaign_ngo_lbpulushi
  get 'campaginngo/lbpulushi_supporters', to: 'campaign_ngo#lbpulushi_supporters', as: :campagin_ngo_lbpulushi_supporters
  
  post 'campaginngo/confirmation', to: 'campaign_ngo#confirmation', as: :campaign_ngo_checkout_confirmation
  post 'campaginngo/confirmation_weixin', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin
  post 'campaginngo/confirmation_weixin/:campaign_id', to: 'campaign_ngo#confirmation_weixin', as: :campaign_ngo_confirmation_weixin_bycampaign

app/models/collection.rb
class Collection < ActiveRecord::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged

    # Try building a slug based on the following fields in
    # increasing order of specificity.
    def slug_candidates
        [
            :name,
            [:name, "#{Collection.where(name: name).count + 1}"]
        ]
    end


    scope :active, -> { where(active: true).order(:sort_order) }
    scope :isnot_destroy,->{where(is_destroy:false)}

    has_many :categories, :dependent => :destroy
    has_and_belongs_to_many :products,->{where is_destroy: false}
    has_many :campaigns

    validates :name, presence: true

    def tile_size
        #if the number of products is greater than 4, return 4 (puts 3 tiles per row)
        #if the number of products is less than or equal to 4, return 6 (puts 2 tiles per row)
        self.products.count > 4 ? 4 : 6
    end

end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::ApplicationController

    def index
        @collections = Collection.isnot_destroy.order(:id)
    end

    def show
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
    end

    def new
        @collection = Collection.new
    end

    def create
        @collection = Collection.new(collection_params)

        # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
        if !@collection.valid?
            message = ''
            @collection.errors.each do |key, error|
                message = message + key.to_s.humanize + ' ' + error.to_s + ', '
            end
            flash.now[:danger] = message[0...-2]
            render action: "new" and return
        end

        @collection.save

        if params[:collection_image].present? && params[:remove_item_image]=="no"
            preloaded = Cloudinary::PreloadedFile.new(params[:collection_image])
            if preloaded.valid?
                @collection.update_attribute(:picture, preloaded.identifier)
            end
        end

        redirect_to admin_collections_url, flash: { success: "组合已创建" }

    end

    def edit
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
    end

    def update
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
        @collection.assign_attributes(collection_params)

        # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
        if !@collection.valid?
            message = ''
            @collection.errors.each do |key, error|
                message = message + key.to_s.humanize + ' ' + error.to_s + ', '
            end
            flash.now[:danger] = message[0...-2]
            render action: "new" and return
        end

        @collection.save
        
        if params[:remove_item_image]=="yes"
           @collection.update_attribute(:picture, "")
        else
          if params[:collection_image].present?
              preloaded = Cloudinary::PreloadedFile.new(params[:collection_image])
              if preloaded.valid?
                  @collection.update_attribute(:picture, preloaded.identifier)
              end
          end
        end

        redirect_to admin_collections_url, flash: { success: "组合已更新" }
    end

    def destroy
        @collection = Collection.friendly.find(params[:id])
        
        if !@collection
          redirect_to admin_collections_url, flash: { danger: "该组合未找到" } and return
        end
        
        if @collection.campaigns.count>0
          redirect_to admin_collections_url, flash: { 
            danger: "组合正在使用，无法删除" } and return
        end
        
        if @collection.products.count>0
          redirect_to admin_collections_url, flash: { 
            danger: "组合正在使用，无法删除" } and return
        end

        @collection.update(is_destroy:true)
        redirect_to admin_collections_url, flash: { success: "组合已删除" }
    end

    private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def collection_params
        params.require(:collection).permit :name, :description, :landing_page_html, :donation_percentage, :picture, :active, :sort_order
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

    def index
        @collections = Collection.isnot_destroy.active
    end

    def show
        @collection = Collection.isnot_destroy.friendly.find(params[:id])
    end

end

app/helpers/admin/collections_helper.rb
module Admin::CollectionsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/admin/collections/_form.html.erb
<%= form_for([:admin, @collection], html: { class: "collection_form" }) do |f| %>
    <fieldset>

        <div class="row">
            <div class="col-md-12">

                <div class="well">
                    <label for="collection_name" class="control-label">名称</label>
                    <%= f.text_field :name, class: 'form-control', placeholder: '名称' %>
                </div>

                <div class="well">
                    <label for="collection_description" class="control-label">描述</label>
                    <%= f.text_area :description, class: 'tinymce', placeholder: '描述' %>
                </div>

                <div class="well">
                    <label for="collection_landing_page_html" class="control-label">登录页HTML</label>
                    <%= f.text_area :landing_page_html, class: "tinymce" %>
                </div>

                <div class="well">
                    <div class="row">
                        <div class="col-md-12">
                            <label>图片 <span style="font-weight: normal">(最佳尺寸: 280*280像素)</span></label>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="image-uploader">
                                        <div id="drop-zone" class="drop-zone">
                                            <div class="row"><div class="col-md-6">
                                                <div class="upload-button-holder" style="position: relative">
                                                    <a class="btn btn-default btn-block upload-button">Choose File</a>
                                                    <%= cl_image_upload_tag(:collection_image, tags: Rails.env, html: { accept:"image/*"}) %>
			  <a href="#" class="remove-image" style="display:none">Remove picture</a>
                                                </div>
                                            </div><div class="col-md-6">
                                                <p class="drop-text"></p>
                                            </div></div>
                                        </div>
                                        <div class="progress progress-striped active" style="display: none;">
                                            <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%; text-align: right; padding-right: 5px;">
                                            <span>0%</span>
                                            </div>
                                        </div>
                                        <span class="status"></span>
                                        <div class="preview">
                                            <% if f.object.picture.present? %>
                                                <%= cl_image_tag f.object.picture, width: 97, height: 94, crop: :limit, class: 'img-responsive' %>
                                            <% else %>
                                                <%= image_tag 'default_upload_logo.gif' %>
                                            <% end %>
                                        </div>
										<div class="remove-preview" style="margin-top:10px; display:<%= f.object.picture.present? ? 'block' : 'none' %>;" data-default-url="<%=asset_path 'default_upload_logo.gif'%>">
											<%= hidden_field_tag :remove_item_image, "no" %>
											
											<button class="btn btn-primary" type="button" style="width:94px;"><span class="text">删除</span></button>
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="well">
                    <div class="row">
                        <div class="col-md-12">
                          <div class="checkbox">
                            <label for="collection_active"><%= f.check_box :active %> 是否启用</label>
                          </div>
                        </div>
                    </div>
                </div>

                <div class="well">
                    <label for="collection_sort_order" class="control-label">排序编号</label>
                    <%= f.text_field :sort_order, class: 'form-control' %>
                </div>

            </div>
        </div>

        <button id="collection-form-submit" class="btn btn-primary" name="commit" type="submit">
            <span class="text">保存 </span> <span class="loader" style="display:none"></span>
        </button>

    </fieldset>
<% end %>

app/views/admin/collections/edit.html.erb
<div id="collections">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h3>编辑: <%= @collection.name %></h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <%= render 'form' %>
            </div>
        </div>

    </div>
</div>

app/views/admin/collections/index.html.erb
<div id="collections" style="padding: 30px 0">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h3>组合</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>名称</th>
                                <th>启用</th>
                                <th>排序编号</th>
                                <th>图片</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @collections.order(:id).each do |collection| %>
                            <tr>
                                <td>
									<% if collection.id>0 %>
                                    	<%= link_to collection.name, admin_collection_path(collection) %>
									<% else %>
										<%= collection.name %>
									<% end %>
								</td>
                                <td>
                                    <% if collection.active %>
                                    <span class="glyphicon glyphicon-ok"></span>
                                    <% end %>
                                </td>
                                <td><%= collection.sort_order %></td>
                                <td>
                                    <%= cl_image_tag collection.picture, width: 50, height: 50, crop: :limit, class: 'img-thumbnail' if collection.picture.present? %>
                                </td>
                                <td>
									<% if collection.id>0 %>
	                                    <%= link_to '删除', admin_collection_path(collection), method: :delete, data: { confirm: '您确定要删除该组合吗?' } %>
									<% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%= link_to '添加组合', new_admin_collection_path, class: 'btn btn-primary' %>

    </div>
</div>

app/views/admin/collections/new.html.erb
<div id="collections">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h3>新组合</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <%= render 'form' %>
            </div>
        </div>

    </div>
</div>

app/views/admin/collections/show.html.erb
<div id="collections">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h3>组合: <%= @collection.name %></h3>
            </div>
        </div>
        <%= link_to "编辑", edit_admin_collection_path(@collection), class: 'btn btn-primary' %>


        <h4>分类</h4>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>名称</th>
                                <th>图片</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @collection.categories.order(:id).each do |category| %>
                            <tr>
                                <td><%= link_to category.name, edit_admin_collection_category_path(@collection, category) %></td>
                                <td>
                                    <%= cl_image_tag category.picture, width: 50, height: 50, crop: :limit, class: 'img-thumbnail' if category.picture.present? %>
                                </td>
                                <td>
                                    <%= link_to '删除', admin_collection_category_path(@collection, category), method: :delete, data: { confirm: '您确定要删除该分类吗?' } %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%= link_to '添加分类', new_admin_collection_category_path(@collection), class: 'btn btn-primary' %>

    </div>
</div>